Name: Provision AWS Infrastructure
on:
  push:
    branches:
      - main
  
jobs:
  provision-AWS-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure the AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1

      - name: Deploy the Cloudformation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: S3DemoStack
          template: .github/workflow/app-dev.yaml
          no-fail-on-empty-changeset: true